name: "tv-score-app"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.new
    ports:
      - 5000:5000

    shm_size: 256m

    develop:
      watch:
        - action: sync
          target: /app
          path: .
          ignore:
            - venv/